ahsan-kamal-sdq/LibraryManagementSystem

.circleci/config.yml

Added the configuration file for CircleCI.
(Need Sana-Ullah to create the project on CircleCI's dashboard as he's the repo admin. Will put a comment here when that is done so we can merge)
Asana Ticket: https://app.asana.com/0/1204411152293714/1204422722661442

CirlceCI config.yml added

---

src/schemas/borrowed.py

Asana Task: https://app.asana.com/0/1204411152293714/1204439508142896
Added the pydantic model for Borrowed
Added the following validations:
- Due date must be greater than issue date
- Return date must be greater than Issue date

[models] Pydantic model Borrowed

---

src/endpoints/borrowed/__init__.py
src/endpoints/borrowed/get/get_borrowed_by_id.py
tests/test_borrowed_get.py

Asana link: https://app.asana.com/0/1204411152293714/1204549582395937/f
Implemented the Get by ID endpoint of Borrowed. Librarian can get any borrowed, user can only get their own.

[API-Borrowed] Get by ID

---

src/endpoints/book/get/get_book_by_id.py
src/endpoints/book/post/book_create.py
src/schemas/book.py
src/schemas/copy.py
tests/test_book.py
tests/test_copy.py

Copy is created automatically for when the book is created.
Added validations and test cases for Book and Copy
Links :
https://app.asana.com/0/1204411152293714/1204570150489893/f
https://app.asana.com/0/1204411152293714/1204570150489895/f

Sohaib Validations [Book, Copy]

---

src/dependencies.py
src/endpoints/auth/auth_utils.py
src/endpoints/auth/post/login.py

Asana link: https://app.asana.com/0/1204411152293714/1204587664973652/f
- Added the is_librarian field to JWT's signature so that we don't have to do a DB call to check in every request

Added is_librarian field to JWT signature

---

src/endpoints/borrowed/__init__.py
src/endpoints/borrowed/get/get_all_borrowed_for_any_user.py
tests/test_borrowed_get.py

Asana link: https://app.asana.com/0/1204411152293714/1204549582395946/f
- Added endpoint to get all borrowed books for a specific user, to be accessible by the librarian
- Wrote required tests

[API-Borrowed] Get all borrowed for any user - (For librarian)

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/pages/BookDelete.tsx
frontend/yarn.lock

Asana link: https://app.asana.com/0/1204411152293714/1204600474221107/f
- Made the frontend runnable by making a minor fix, specifically fixing an import in the BookDelete.tsx file

[Frontend] some minor fixes to make it run

---

src/responses.py

This PR adds separate response functions in the Project. So, all responses should be consistent and have same format.
There are three response functions have been engineered in this PR.
- **custom_response(status_code,data, details)** The status code for this function and other two args can be tweaked.

Sana Ullah: Separate Response functions.

---

frontend/src/axios.tsx
frontend/src/components/pages/Login.tsx
main.py

Asana Link: https://app.asana.com/0/1204411152293714/1204610053252976/f
- Integrated the login API with frontend
- Had to add a CORS middleware in the API for the frontend to send requests

[Frontend] Integrate Login API

---

frontend/package.json
frontend/src/CustomTypes.tsx
frontend/src/axios.tsx
frontend/src/components/BookForm.tsx
frontend/src/components/pages/BookCreate.tsx
frontend/src/components/pages/BookDetailsContainer.tsx
frontend/src/components/pages/BookDetailsPresentation.tsx
frontend/src/components/pages/BookListContainer.tsx
frontend/src/components/pages/BookUpdate.tsx
frontend/src/components/pages/Home.tsx
frontend/src/components/pages/Login.tsx
frontend/src/components/pages/__test__/BookDetailsPresentation.test.tsx
frontend/src/components/pages/__test__/BookListPresentation.test.tsx
frontend/src/components/pages/__test__/__snapshots__/BookDetailsPresentation.test.tsx.snap
frontend/src/contexts/AuthContext.tsx
src/endpoints/book/post/book_create.py

Asana Link: https://app.asana.com/0/1204411152293714/1204618434482827/f
- Integrated the Books API with frontend. Specifically the following operations:
- List books
- Book Details
- Create Book
- Update Book
- Delete Book (Integrated but not yet working because soft delete is not implemented)

[Frontend] Integrate Books API

---

src/endpoints/borrowed/__init__.py
src/endpoints/borrowed/put/return_borrowed_for_any_user.py
src/endpoints/borrowed/put/return_borrowed_for_user.py
src/endpoints/borrowed/put/update_borrowed_by_id.py
src/schemas/borrowed.py
tests/test_author.py
tests/test_borrowed_put.py

This PR adds two endpoints for the returning borrowed Items.
- **return borrowed item for logged-in user** User can return its own borrowed items.
- **Librarian can return the book of any user by specifying the borrowed id.** Librarian can return for any user.
https://app.asana.com/0/1204411152293714/1204601040566438/f

Sana Ullah: [Borrowed] Two endpoints for returning copies

---

src/endpoints/borrowed/post/create_borrowed.py
src/endpoints/borrowed/put/return_borrowed_for_any_user.py
src/endpoints/borrowed/put/return_borrowed_for_user.py
src/status_constants.py
tests/test_borrowed_post.py
tests/test_borrowed_put.py

This PR fixes the Endpoints of:
- **Borrowed POST** with respect to new status Table.
- **Borrowed PUT (return borrowed) ** with respect to new Status Table.
**Please Check it Critically and Leave Comments.**
https://app.asana.com/0/1204411152293714/1204642324377428/f

Sana Ullah: [Fixed Borrowed POST and PUT endpoints]

---

src/dependencies.py
src/endpoints/auth/auth_utils.py
src/endpoints/auth/post/login.py
src/endpoints/author/delete/delete_by_id.py
src/endpoints/author/get/get_by_id.py
src/endpoints/author/put/update_author.py
src/endpoints/borrowed/get/get_borrowed_by_id.py
src/endpoints/borrowed/post/create_borrowed.py
src/endpoints/borrowed/put/return_borrowed_for_any_user.py
src/endpoints/borrowed/put/return_borrowed_for_user.py
src/endpoints/borrowed/put/update_borrowed_by_id.py
src/endpoints/copy/delete/copy_delete.py
src/endpoints/copy/get/get_copy_by_id.py
src/endpoints/copy/post/copy_create.py
src/endpoints/copy/put/copy_update.py
src/exceptions.py
tests/test_auth.py

This PR fixes the exceptions in borrowed, copy, auth, author and dependencies files.

Sana Ullah: [Modified Exceptions]

---

src/endpoints/book/delete/book_delete.py
src/endpoints/book/get/get_book_by_id.py
src/endpoints/book/get/get_books_by_query.py
src/endpoints/book/put/book_update.py
tests/test_author.py
tests/test_book.py
tests/test_user.py

This PR Modifies the **Book API** to incorporate the newly added **is_deleted** column.
**Changes:**
_**NOTE:**_
https://app.asana.com/0/1204411152293714/1204670809151544/f

Sana Ullah: [Book API Soft_Delete]

---

src/endpoints/borrowed/get/get_all_borrowed_for_any_user.py

This PR adds the Pagination to a Borrowed endpoint.
https://app.asana.com/0/1204411152293714/1204657648418269/f

Sana Ullah: [Borrowed endpoint pagination]

---

src/endpoints/author/delete/delete_by_id.py
src/endpoints/author/get/get_all_authors.py
src/endpoints/author/get/get_by_id.py
src/endpoints/author/put/update_author.py

https://app.asana.com/0/1204411152293714/1204655026249277/f
Implement soft delete on author api's get, put and delete routes.

Talha/[Author API] Soft delete

---

src/endpoints/copy/delete/copy_delete.py
src/endpoints/copy/get/get_copies.py
src/endpoints/copy/get/get_copies_by_book_id.py
src/endpoints/copy/get/get_copy_by_id.py
src/endpoints/copy/put/copy_update.py
tests/test_author.py
tests/test_copy.py
tests/test_user.py

This PR Modifies the **Copy API** to incorporate the newly added **is_deleted** column.
**Changes:**
_**NOTE:**_
https://app.asana.com/0/1204411152293714/1204670809151547/f

Sana Ullah: [Copy API Soft Delete]

---

src/endpoints/book/delete/book_delete.py
src/endpoints/book/get/get_book_by_id.py
src/endpoints/book/get/get_books_by_query.py
src/endpoints/book/put/book_update.py
src/endpoints/language/delete/delete_language_by_id.py
src/endpoints/language/get/get_all_languages.py
src/endpoints/language/get/get_language_by_id.py
src/endpoints/language/put/update_language_by_id.py
tests/test_author.py
tests/test_book.py
tests/test_language_api.py
tests/test_user.py

This PR Modifies the **Language API** to incorporate the newly added **is_deleted** column.
**Changes:**
_**NOTE:**_
https://app.asana.com/0/1204411152293714/1204670809151553/f

Sana Ullah: [Language API] Soft Delete

---

src/endpoints/genre/delete/delete_genre_by_id.py
src/endpoints/genre/get/get_all_genre.py
src/endpoints/genre/get/get_genre_by_id.py
src/endpoints/genre/put/update_genre_by_id.py
tests/test_author.py
tests/test_genre_api.py
tests/test_user.py

This PR Modifies the **Genre API** to incorporate the newly added **is_deleted** column.
**Changes:**
_**NOTE:**_
https://app.asana.com/0/1204411152293714/1204670809151556/f

Sana Ullah: [Genre API] Soft Delete

---

src/endpoints/status/delete/status_delete.py
src/endpoints/status/get/get_status.py
src/endpoints/status/get/get_status_by_id.py
src/endpoints/status/put/update_status_by_id.py
tests/test_author.py
tests/test_status_api.py
tests/test_user.py

This PR Modifies the **Status API** to incorporate the newly added **is_deleted** column.
**Changes:**
_**NOTE:**_
https://app.asana.com/0/1204411152293714/1204674036909710/f

Sana Ullah: [Status API] Soft Delete Implementation

---

main.py
src/endpoints/user/user_utils.py

Needed to include frontend server's IP to CORS so that frontend can communicate with the backend server.

Include frontend server IP to CORS
